### ISSUE TITLE
Invalid transaction value on Paypal standard return

### ISSUE THREAD

**Issue by tplessis** [responsiv/pay-plugin#11]
Hi,

Error appears on a redirection after a successful payment :

![sans-titre-2](https://cloud.githubusercontent.com/assets/1204462/13477985/14314542-e0cf-11e5-9caf-72819f7b79e0.jpg)

**Comment by daftspunk** [comment]
What October build are you using?

**Comment by tplessis** [comment]
Build 316.

**Comment by daftspunk** [comment]
This plugin has been tested with the unreleased `stable` branch of [October](https://github.com/octobercms/october) only. I hope to have this plugin officially released soon.
