### ISSUE TITLE
Cannot edit a payment gateway

### ISSUE THREAD

**Issue by tplessis** [responsiv/pay-plugin#12]
Hi,

Just after creating a new Paypal standard gateway, i was unable to update it. This message appears :

"Unable to find gateway with alias " on line 110 of /var/www/henricapitant_prod/public/plugins/responsiv/pay/controllers/PaymentMethods.php"

**Comment by alxy** [comment]
It appears, you did something wrong when adding your own custom gateway. If you open source your fork of the plugin, we could have a look on it.

**Comment by daftspunk** [comment]
Unable to replicate, more info needed
