### ISSUE TITLE
Adding Skrill as payment method causes error

### ISSUE THREAD

**Issue by MilosStanic** [responsiv/pay-plugin#22]
When adding Skrill as payment gateway, filling form, and pressing "Save", error pops up, saying that it was unable to find field `test_mode` in table `responsiv_pay_methods` table, as it was trying to write it as a table field instead of JSON array var in `config_data` field.

**Comment by daftspunk** [comment]
Not sure if Skrill supports a test mode, this must have occurred from copying the gateway class from another, probably PayPal.
