### ISSUE TITLE
Reason for ``newQuery``

### ISSUE THREAD

**Issue by alxy** [responsiv/pay-plugin#23]
Is there any specific reason for the ``newQuery()`` call here: https://github.com/responsiv/pay-plugin/blob/master/models/InvoiceStatusLog.php#L72

This leads to an $invoice instance with outdated data, as the new status is not passed to the instance. I copied this class to my own plugin and it costed me quite a while why I always got the old data, while the database already contained the new.

Maybe this should be changed to a simple ``update`` call if there is no good reason.

**Comment by daftspunk** [comment]
No reason. Pull request

**Comment by alxy** [comment]
I know the reason. It breaks the functionality of deferred bindings, in this case: deferred line items are no longer comitted, when the invoice is saved. Could not debug it any further, but if I remove the change, everything works as expected.

**Comment by daftspunk** [comment]
As per the contribution guidelines, please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by alxy** [comment]
To summerize: There is no issue with the current code. The [original PR](https://github.com/responsiv/pay-plugin/pull/24) proposed a change to simplify the code (and adds value as the $invoice instance is updated with the correct data), but breaks existing functionality. In this case, deferred ``LineItem`` instances were no longer correctly bound to their parent.
