### ISSUE TITLE
Related object to the invoice

### ISSUE THREAD

**Issue by chrisvidal** [responsiv/pay-plugin#25]
Today there is a 'related' relation in the invoice model which is great.
However not sufficient in the case where the invoice is having multiple items (in my case multiple subscriptions) that need to be activate upon payment completion.
Hence, who would @daftspunk to handle this scenario please ?

**Comment by daftspunk** [comment]
The `InvoiceItem` model now has a `related` relation that you can use for associated multiple related models to a single invoice. Hope this helps.
