### ISSUE TITLE
Taxes and discounts

### ISSUE THREAD

**Issue by pbsmultimedia** [responsiv/pay-plugin#26]
Hello, thanks for this great plugin.

Been testing and found some issues:
- Taxes are not applied 
- Discount makes a strange value, like:

DESCRIPTION QTY PRICE DISCOUNT AMOUNT
another test    1   250.00  5.00     -1000.00

**Comment by daftspunk** [comment]
As per the contribution guidelines, please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by acasar** [comment]
@daftspunk Regarding discount I noticed that it needs to be entered like a decimal. So for 5% discount you need to enter 0.05 and not 5. Is this expected behavior?

![image](https://cloud.githubusercontent.com/assets/6329543/24495873/d425c052-1536-11e7-988f-ed163cc3571a.png)

**Comment by daftspunk** [comment]
I would think not, feel free to fix it.

**Comment by triasrahman** [comment]
I found the same issue. 

1. I created a line item with price: 10,000, qty: 1, and discount: 0.5
![image](https://cloud.githubusercontent.com/assets/7110859/25288202/95eea21c-26ee-11e7-9270-e6a97b6bd4d9.png)
It works to discount 50% on a line item.

2. After I save the invoice, something weird happen. How come the total can be 4,999.50 ?
![image](https://cloud.githubusercontent.com/assets/7110859/25288235/c90d738a-26ee-11e7-98c3-171262146ff6.png)

I figured out on the `invoice` row has discount value: 0.5, and subtotal 5,000. Why do you reduce the subtotal if it's already reduced ?

I think it's crucial. Please fix it soon.

Thank you

**Comment by raakesh** [comment]
@triasrahman @pbsmultimedia I was having same kind of problem while applying discount to the items.
I've created new issue #33 with a proper issue template and I also created a PR #34  which solves discount problem.

**Comment by daftspunk** [comment]
Addressed in #33
