### ISSUE TITLE
This is not any issue but need some explanation

### ISSUE THREAD

**Issue by shajidkhn26** [responsiv/pay-plugin#27]
Dear author of the plugin.your plugin is very helpful but need more descriptive documentation of how to use it.

**Comment by daftspunk** [comment]
Thanks for your interest. This is a beta plugin at the moment and should only be used by the adventurous.

**Comment by mosid** [comment]
> Thanks for your interest. This is a beta plugin at the moment and should only be used by the adventurous.

Is this still the case now @daftspunk ?

**Comment by Alex360hd** [comment]
Same here, I'm planning to develop an ecommerce plugin, and I wonder if I can rely on this plugin in order to manage taxes, payments and invoices, or if it's better to create my own implementation of all that things

**Comment by daftspunk** [comment]
Some plugins I use for personal projects and release them for the world to study. There are 0 PRs (maintained) but largely undocumented (for the brave)

Hope this answers the question
