### ISSUE TITLE
Undefined index: country

### ISSUE THREAD

**Issue by jvanremoortere** [responsiv/pay-plugin#28]
When trying to add a "line item" to my invoice I get the following error:

```
"Undefined index: country" on line 334 of ...\plugins\responsiv\pay\models\Tax.php
```
Although I have only 2 active countries in my LOCACTION > Countries & States, when trying to setup the Tax tables for the Payments plugin, I can only select AU - CA - GB - US - AF - AX - AL - DZ - AS  - AD and Any Country to use in my "Rates" table. Because my active countries are not listed I've used "Any country".

The user I'm trying to make an invoice for is from Belgium.

**Comment by goeroe** [comment]
It seems that these two have nothing to do with each other. I've enabled United Kingdom and changed the country of the user to United Kingdom.

Then I've edited the Tax table to United Kingdom and try to add a line to the invoice. I still get the same error "Undefined index: country" on line 334.

**Comment by Alex360hd** [comment]
+1 here, when I try to save a new invoice in the backend, I get this error.
