### ISSUE TITLE
Recurring Invoice?

### ISSUE THREAD

**Issue by AugmentBLU** [responsiv/pay-plugin#30]
Hello,

I'm just wondering if you might be able to enhance this plugin by including recurring invoices? Maybe allow a cron to run every 12/24 hours to check who's due to pay in the next 7 days and auto invoice.

Some control over this would be great, maybe even make a premium version. It might go very well with the support plugin as well which I'm interested in.

Thanks.

**Comment by alxy** [comment]
Are you maybe looking for a [subscription plugin](https://github.com/responsiv/subscribe-plugin)? This is in the makes (I guess) and will be a paid one.

**Comment by AugmentBLU** [comment]
Could be - what I'm after is being able to create a service that a client pays for on a monthly basis. I currently use WHMCS to bill clients for hosting related items and deals with support requests but it's overkill for what I'm using it for. I just need a fairly simple recurring payment system, with reminders. 

Do you have any screenshots or feature list?

**Comment by alxy** [comment]
It will be very similar to Laravel Spark, at least that was the last bits I heard from @daftspunk 
Some key differences and design goals can be found in the corresponding theme repo: https://github.com/responsiv/spark-theme

Your use case however, sounds a lot like a good one for subscription based systems.

**Comment by AugmentBLU** [comment]
I was actually checking Spark just yesterday - what a coincidence. 

I definitely need something that is subscription based, something that doesn't depend on an online payment system. Some clients must use bank transfer for payments so it would be great to just invoice on a monthly basis - here's what you are due and here's the bank details.

As I said, I currently use WHMCS which I hate - it won't work on a load balanced server due to it's poor support of session handlers so I'm looking towards a more native approach.

**Comment by AugmentBLU** [comment]
Hopefully there's some word on what's install for the subscription plugin. Would be amazing if it had the features I need... bye bye WHMCS! 

I'd purchase that and the support plugin - fingers crossed.

**Comment by daftspunk** [comment]
Yes, this is in the works. It will utilize this payment plugin. Thanks for your interest!
