### ISSUE TITLE
Extra Fields

### ISSUE THREAD

**Issue by AugmentBLU** [responsiv/pay-plugin#31]
Hello,

I'm currently testing this plugin and I'm liking it. I was hoping that new fields could be added to enhance the use.

Rather than a single address line, could this be split in to line 1/2/3? I know that the User+ plugin has a single line address, but that could do with being enhanced too.

Also, being able to CC another email address would be handy. Some of my clients have an accounts department and like to be CC'd in on invoicing but not necessarily have login details for an account.

Thanks!

**Comment by alxy** [comment]
You can perfectly do this by creating your own plugin and extending this one (just like the UserPlus plugin does with User). Just create a migration that creates the extra fields in the database and then extend the forms and lists to your needs.

**Comment by daftspunk** [comment]
Or you can submit a PR to introduce it? Easy done!
