### ISSUE TITLE
Problem with grand total values when discount is applied.

### ISSUE THREAD

**Issue by raakesh** [responsiv/pay-plugin#33]
##### Expected behavior
When you create line item where quantity = 1, unit price = 100 and discount(%) = 0.1 the grand total value in the Invoice should be displayed as 90.

##### Actual behavior
When you create line item with quantity = 1, unit price = 100 and discount(%) = 0.1 the grand total value in the Invoice is displaying as 89.90.

##### Reproduce steps
1. Create a new invoice by clicking on New Invoice button.
2. Create a line item with  quantity = 1  and unit price = 100.
3. Add discount(%) = 0.1.
4. Click on Create and Close button.

##### October build
415

@daftspunk In [Invoice model](https://github.com/responsiv/pay-plugin/blob/master/models/Invoice.php#L178) while calculating grand total I don't think there is need for deducting discount(in percentage) from subtotal, since discount value is already deducted from the subtotal in InvoiceItem. So [184](https://github.com/responsiv/pay-plugin/blob/master/models/Invoice.php#L184) line in Invoice.php should be 
```php 
$this->total = $subtotal + $tax;
```
rather than
```php 
$this->total = ($subtotal - $discount) + $tax;
```

**Comment by triasrahman** [comment]
When you'll update this bug fix?
