### ISSUE TITLE
Incorrect integer value: '[1]'

### ISSUE THREAD

**Issue by felixmpa** [responsiv/pay-plugin#39]
Trying to create an invoice from backend its show me the following error:
-General error: Incorrect integer value: '[1]' for column 'template_id' at row (SQL: insert into "responsiv_pay_invoces".

I figuered out the problem on invoice model.

```
 public function setDefaults()
    {
        if (!$this->country_id) {
            $this->country = Country::first();
        }

        if (!$this->state_id) {
            $this->state = State::first();
        }

        if (!$this->template_id) {
            //Adding the first method returns the first element and not array '[1]'
           $this->template_id = InvoiceTemplate::pluck('id')->first();
        }
    }
```
 
Note I'm using the last version with laravel 5.5.

**Comment by daftspunk** [comment]
???

**Comment by felixmpa** [comment]
Sorry I updated the issue.

**Comment by codacopia** [comment]
I have this same issue.  It was resolved by adding your edit.  Is this something that we can get resolved in the repo for future updates?
