### ISSUE TITLE
How to configure countries available when creating a new tax rule

### ISSUE THREAD

**Issue by ghost** [responsiv/pay-plugin#51]
Hello,

I don't find a way to change the countriy dropdown list of the tax rates datatable.

I believed it was sync with the enabled countries of the rainlab.location module, but it doesn't seems to be the case.

Thank you for your help

Alex

**Comment by Alex360hd** [comment]
Hi,

By reviewing the code, I noticed that the getCountryList method in tax model have a limit in it's country request : 

near line 364 in Tax.php : 

    $countries = Country::limit(10)->lists('name', 'code');

I don't understand the purpose of that limit that should just be removed. I also suggest to just display enabled countries, so, that line 364 would be changed for this : 

    $countries = Country::isEnabled()->lists('name', 'code');

If it's ok for you, I can create a PR for this (even if a PR for a single line seems to be overkill to me ^^)
