### ISSUE TITLE
Offline payment : how to validate ?

### ISSUE THREAD

**Issue by ghost** [responsiv/pay-plugin#52]
Hello,

I created an offline payment to see how it behave on frontend. When I'm on the payment form, I can switch between the different payment methods, but for offline payment, I have no submit buttons that would allow me to validate the form and process the payment.

Regards,

Alex

**Comment by FlusherDock1** [comment]
Offline is stands for offline payments, through bank checks and etc. And to confirm payment, customer must contact web-site administration and send them check or etc.

Then you have to validate it manually from backend.

**Comment by PubliAlex** [comment]
I agree with you, but the frontend form should, at least, have a "submit" button in order to receive the order and display a success message to the customer.

**Comment by FlusherDock1** [comment]
>  have a "submit" button

Submit what? 

There are invoice. Go pay it. Write comment in transaction or etc. When administration get money on their balance they will close invoice with "paid" status.
