### ISSUE TITLE
Please add an option to download or email an invoice as PDF

### ISSUE THREAD

**Issue by briddle** [responsiv/pay-plugin#56]
Hi,

It would be awesome if you could add an option to download or email an invoice as PDF.

**Comment by briddle** [comment]
Hi,

I would like to extend this plugin myself with some additional buttons. Would you be willing to add the following line above the delete button in controllers/invoices/_preview_toolbar.htm (this would allow my plugin to insert some new buttons):

`<?= $this->fireViewEvent('responsiv.pay.extendPreviewToolbar') ?>`

**Comment by daftspunk** [comment]
You have two options:

1. Extend the plugin, submit a pull request to add the hook
2. Submit a pull request to add the feature natively

In either case a pull request is needed and you can consider (1) pre-approved, (2) is dependant on you to produce work at the same quality that is there already.

Thanks!
