### ISSUE TITLE
Separate plugins ?

### ISSUE THREAD

**Issue by ghost** [responsiv/pay-plugin#58]
Hello,

I would like to discuss about the possibility to separate this plugin into 3 plugins : one for taxes, one for payments and one for invoices.

In fact, I'm working on an more complete shopping experience and I would like to rely on your taxes and payment methods system because I don't want to reinvent the wheel.

It sounds more logical to me to separate things, like rainlab did with location or user plugin you use, and like you did with the currency plugin. Existing users would have no drawback if plugins are separated with dependencies, and developpers would have good standardized tools in order to develop their own solutions.

In that logic, I would also suggest to move the taxes and payments methods configuration pages in the settings menu, to be more inline with location and currency plugin.

What do you think about these ideas ?

**Comment by PubliAlex** [comment]
After some months, I don't see many activities around this plugin. Even PR are ignored. Is it still maintained ? I wonder if it's a good idea to consider it could handle some generic stuff like tax or payment management if it's not maintained anymore.

**Comment by daftspunk** [comment]
Thanks for your feedback. We prefer to keep this as one plugin for now
