### ISSUE TITLE
Invoice discount doesn't represent the real value

### ISSUE THREAD

**Issue by triasrahman** [responsiv/pay-plugin#64]
**Expected behavior**

After creating several discounted invoice items:
- Item 1 => Qty: 1, Price: $1000, Discount: 20%
- Item 2 => Qty: 2, Price: $1500, Discount: 50%
- Item 3 => Qty: 1, Price: $10000, Discount: 80%

Invoice Discount = $200 + $1500 + $8000 = $9700
(should be the difference in the base price and discounted price)

**Actual behavior**

After creating several discounted invoice items:
- Item 1 => Qty: 1, Price: $1000, Discount: 20%
- Item 2 => Qty: 2, Price: $1500, Discount: 50%
- Item 3 => Qty: 1, Price: $10000, Discount: 80%

Invoice Discount = 150%
(saved 1.50 in database, sum of all percentage discount)

This value doesn't represent the real value of invoice discount.

**Reproduce steps**
Create a new invoice by clicking on New Invoice button.
Create several invoice items with discount.
Click on Create and Close button.

**October build**
466

**Comment by daftspunk** [comment]
Great bug report, thank you
