### ISSUE TITLE
Incorrect discount amount

### ISSUE THREAD

**Issue by rajakhoury** [responsiv/pay-plugin#67]
Hi,
 
The invoice item has a discount data type of `decimal(15,2)` so values should be inserted as a percentage but the caluclation treats the amount as a fractional percentage e.g 1% = 0.01. This is a leading to negative totals or 0s.

In InvoiceItem Model,  `$discountAmount = $this->price * $this->discount;` should be `$discountAmount = $this->price * ($this->discount / 100)`  or should change the column to `decimal(5,4)` 

Also, adding a validation rule would help avoid incorrect inputs.

**Comment by daftspunk** [comment]
Hi,

Thanks for this report

This could be a breaking change, however, if you submit a pull request we'd be happy to review it. The preference would be to implement it as `discount / 100` instead of changing the column decimal type

**Comment by daftspunk** [comment]
Discounts have been refactored in v2 of this plugin. Now when a percentage is used, it resolves to a fixed amount. A fixed amount can also be provided.

![image](https://github.com/user-attachments/assets/eba50235-02a8-4534-960e-a0cc3b9d7b1a)
